# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiTCL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_PCL', models.IntegerField(blank=True, null=True)),
                ('PCL_amount', models.FloatField(blank=True, null=True)),
                ('TCL_USED', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GetCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ethereum', models.FloatField()),
                ('Bitcoin', models.FloatField()),
                ('Euro', models.FloatField()),
            ],
        ),
    ]
