# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confitcl',
            name='TCL_USED',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
