# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_confitcl_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confitcl',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConfiTCL',
        ),
    ]
