# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_buy'),
        ('accounts', '0008_auto_20171029_1129'),
    ]

    operations = [
    ]
